### ISSUE TITLE
WIndows Desktop App regularly crashing

### ISSUE THREAD

**Issue by markpos** [toggl/toggldesktop#1336]
WIndows 8.1, all updates applied.

Toggl Desktop 7.2.36.

It's crashing regularly on both my desktop and laptop, so seems not to be installation specific.

Crashes are fairly random, when starting and/or stopping tasks.

**Comment by IndrekV** [comment]
We have uploaded a new beta version (7.2.76) that should fix this crashing issue. Please select beta channel from About view and wait for about 5 minutes for the application to get the update in background then restart the app to start using the new version.

**Comment by markpos** [comment]
I've updated to the beta 7.2.76 version, but the app is still crashing. Often crashes are when stopping a running task. However, also crashes at other random times.

**Comment by davidtessier** [comment]
I have this issue too. I tried the desktop app a year ago, mentioned that it crashed, and gave up because there was no help. A year later I tried it again on what I can only hope is an updated version and it still crashes on a fresh install. When I start the app, I see the gray icon appear in my task-bar icons but within a few seconds it disappears. Running Windows 7.
