### ISSUE TITLE
WPF task entry list sometimes does not properly redraw after window refocus

### ISSUE THREAD

**Issue by amulware** [toggl/toggldesktop#1375]
User is using Windows 7.
(see case 164135)

So far I could not reproduce this on Windows 8.1.

Screenshots:
![screen1](https://cloud.githubusercontent.com/assets/3987892/8180346/4f57b2de-141d-11e5-99ad-57a6312953b3.gif)
![screen2](https://cloud.githubusercontent.com/assets/3987892/8180345/4f5501f6-141d-11e5-87f8-e141e6b87693.gif)
![screen3](https://cloud.githubusercontent.com/assets/3987892/8180347/4f580626-141d-11e5-99d3-94bf49f2ebb6.gif)

**Comment by amulware** [comment]
This can apparently also happen just randomly by moving the window, one user reports. (see case 166596)
That user also runs Windows 7.

**Comment by amulware** [comment]
I was able to partly reproduce this on Windows 7. The problem seems to be unique to that operating system.

**Comment by amulware** [comment]
It seems this can also happen on Windows 8, though most  reports are from Windows 7 users.
I was able to reproduce this on a virtual machine with, however not on another actual machine (both Windows 7).

All research so far indicates that this may be a problem in the framework, or even graphics driver.
I encourage everybody who is experiencing this problem to update their graphics drivers (also make sure to update the drivers of your integrated GPU, if you have one - most laptops do these days).
If you do, please let us know whether it helps with this problem!

Regarding what we can do to fix this from our side, the issue seems to entirely dissappear if WPF hardware acceleration is disabled (another indicator that the driver or some other low level part of the framework is at fault). This is not an ideal solution however, since it decreases the application's performance.

We could consider leaving this as an option to the user, in case updating graphics drivers does not help, or is not possible.

**Comment by slav** [comment]
Updating graphics drivers to the latest (NVidia) didn't resolve the issue.

**Comment by amulware** [comment]
Just do make sure: Could it be that you have an integrated GPU (most likely from Intel), that the program may be rendering on? If so, could you check those drivers as well?

And yes, the latest stable release included a complete rewrite of the time-entry-list (see #1349), to solve performance problems and crashes users with many time entries were experiencing.
We moved that part of the interface from Winforms to WPF, which is no doubt the cause of the issue.

**Comment by slav** [comment]
I do have integrated GPI as well, however upgrading to the latest Intel drivers, including graphics driver as of 6/5/2015 had no effect. It's still broken. The only thing that seems to help is to completely disable WPF hw optimization.

**Comment by jackplug** [comment]
I have an Nvidea card too and it already has the latest drivers - I see the problem on Win 8.1 Pro (and it started with 7.2.172 as I reported previously https://github.com/toggl/toggldesktop/issues/1396#issuecomment-116704956)

**Comment by amulware** [comment]
From the comments here, and in other support channels, it seems that the problem is either not (always) graphics driver related, or that even some up to date drivers have the issue (unlikely).

Since disabling hardware rendering fixes the problem at least on the machine where I can reproduce the issue, I suggest we add a user setting to do exactly this (I would shy away from disabling it for all users, for performance reasons).

**Comment by jackplug** [comment]
Apologies if I have missed something, but *how* exactly would you disable WPF hw optimization? Or is it the case that a user setting could appear within a reasonably short space of time?

**Comment by amulware** [comment]
For now WPF hardware acceleration can be disabled machine-wide (all programs that use it) using a registry key, see here: http://stackoverflow.com/a/2169657/1175259

However, that is very much a shotgun approach to this specific problem.

I cannot make any promises regarding the time frame of the user setting right now, but I hope we can have it available next week - at least in the beta branch.

**Comment by jackplug** [comment]
ahh, I see - I don't really want to take this machine-wide approach so I will wait for the user setting to appear

**Comment by slav** [comment]
Not sure which .NET you target, but perhaps as a setting this will work eventually? https://msdn.microsoft.com/en-us/library/system.windows.media.renderoptions.processrendermode.aspx

**Comment by amulware** [comment]
Yes, that is what we will be using most likely. It looks promising in our tests so far.

**Comment by amulware** [comment]
This commit just now should disable all WPF hardware accelerated rendering, which hopefully fixes this issue. I'm leaving this open until we confirm this with more testing.

**Comment by AsciiSmoke** [comment]
I have Windows 8.1 Enterprise running on an NVidia GeForce 9400 GT and I have this issue too. It's extremely annoying as every update to the Toggl window requires me to run my mouse over the window to get it to re-draw.

Here is an example of a half-redrawn window, if I run my mouse over the window it'll redraw properly (presumably as the mouse-over effect is applied):

![image](https://cloud.githubusercontent.com/assets/12941199/8669547/71ffe472-2a0d-11e5-810d-c1a81f98ec2d.png)

**Comment by amulware** [comment]
@AsciiSmoke, @jackplug, @slav:

We just released a new beta version which should fix these rendering issues for everyone.

You can update to the beta by selecting it in the programs about window. Give it a few minutes to download the update in the background, and then restart the program. It should update automatically. (The beta also includes a completely new edit window, so you can check that to make sure you got the beta.)

It would be great if you can report back if the problems are fixed for you now.

**Comment by slav** [comment]
I'm getting a lot of "Abort due to constraint violation" messages above the timer now. Haven't seen it before. Closing it with X just brings it back up soon after (a couple of seconds). Any idea what's going on with it? Haven't seen it before.

**Comment by slav** [comment]
Also, it didn't fix the rendering issue. Still everything is going blank. On 7.2.204

**Comment by amulware** [comment]
I thought we had the constraint violation thing fixed (see #1415). We'll look into that.

And that the rendering is still broken is bad. I will look into this again as well.

**Comment by jackplug** [comment]
I am seeing multiple 'Abort due to constraint violation' messages (multiple, as in, "Abort due to constraint violation. Abort due to constraint violation  [X]" - where [X] is the close button :)) and it also reappears  Plus I am still seeing the rendering issue, but it fixes itself a little better than previously. It's still quite irritating, though

**Comment by IndrekV** [comment]
@jackplug Please send feedback from the app, that way we get the log files and can investigate. Mention  in the feedback that the logs are for Tanel.

**Comment by jackplug** [comment]
I am seeing the new edit window, but I see a different version number to @slav - mine says 7.2.196. @IndrekV, I have now sent feedback from the app mentioning Tanel

**Comment by jackplug** [comment]
Plus, I am also seeing a slightly bigger problem in that the timer no longer seems to work at all.

Correction, it seems like it may be working, but I am seeing lots and lots of entries with 'no description', and times between 1 and 11secs

**Comment by IndrekV** [comment]
@jackplug Please get the latest version. We've actually already addressed this `Abort due constraint..` issue in the later version. Also `Clear Cache` (from the cog menu) clears the old local data that is creating the error.

**Comment by amulware** [comment]
The newest beta version also contains the proper fix for the original graphical glitch.

**Comment by jackplug** [comment]
I don't seem able to download the newest version (opened about, switched to **beta**, waited a few minutes, then restarted). I then cleared the cache and had to log back in. The program then crashed completely :(

**Comment by jackplug** [comment]
Ahh, NOW it seems to work. I switched to **dev**, got version 7.2.205, and now everything works as it did originally. Maybe I will try switching back to beta

**Comment by IndrekV** [comment]
@jackplug I advise you to switch back to Beta as dev channel has a lot of builds and can be quite broken at times.

**Comment by jackplug** [comment]
OK, I would but beta is still not downloading for me for some reason - it's the same as I said in https://github.com/toggl/toggldesktop/issues/1375#issuecomment-123249774 Would it be easier to clear cache, uninstall then reinstall, THEN switch to beta, I wonder? Would there be some other setting that I should clear first, before reinstalling?

**Comment by IndrekV** [comment]
7.2.205 is the latest version in Beta. If you have the same version then there's nothing to download.

**Comment by jackplug** [comment]
Ahh, so that explains it! :)

**Comment by jackplug** [comment]
...and, as I said previously, so far so good... I don't see any problems

**Comment by jackplug** [comment]
and just as I say that, up pops the ```abort due to constraint...``` msg. I close it, then I cannot start the timer again :(

**Comment by tanel** [comment]
hi there, can you report the same issue from the desktop app itself? then its sends us the log files and we can take a look what went wrong!

**Comment by jackplug** [comment]
OK, It completely crashed on me, so I closed it with task manager, and now it *seems* to be working. If it does something weird again, I post an issue from the app

**Comment by jackplug** [comment]
I **would** have sent feedback via the app if it were possible.

1. the ```abort due to constraint...`` msg`appears so I close it,
2. then the timer will not stop,
3. so I go to Send Feedback... and the app crashes with a broken 'Send Feedback' window 

(TaskManager helpfully reports 'Not responding' so I need to end the task)

**Update:** on reopening the app, the problem still existed. I left the error message alone and went straight to 'Send feedback', and it worked

**Comment by jackplug** [comment]
...and now, whenever I reopen the app, the timer continues and I cannot stop it (the abort msg appears after about 5 seconds)

**Comment by jackplug** [comment]
now I see something different. Opened the app again, my timer then stops, then I see message 'cannot pull user data when logged out'. So, I have logged out an logged in, and it seems ok for now. Timing values on the website look to be ok too

**Comment by tanel** [comment]
anyone with the constraint error - please contact support@toggl.com since we need some data from your computer to resolve this issue.

**Comment by jackplug** [comment]
@tanel sorry I did not see your email response earlier from support@toggl.com asking me to test a version that you linked to - I am using my office computer right now. But, I will test it in a few minutes and let you know

**Comment by tanel** [comment]
@jackplug it's ok, many thanks for helping us with the bug reports!

**Comment by jackplug** [comment]
So, firstly, I uninstalled the desktop app and removed all trace of it (well, deleted Toggl and TogglDesktop in my installation dir anyway). Then II installed TogglDesktopInstaller-7_2_205-2015-07-21-12-45-20.exe as requested, and on launch, it crashed.

I closed the task using Task Manager and then reopened, and it seems to work ok for about 10 minutes before displaying the ``abort due to constraint...`` msg. I will send you feedback from the app in a moment. I signed the feedback with @jackplug so that you know it's me :)

**Comment by slav** [comment]
Sent feedback from 7.2.204. Will try to do it from older version when and if it updates.

**Comment by slav** [comment]
on 7.2.206 things seem to be good and no crashes so far.

**Comment by jackplug** [comment]
Now running 7.2.206 (beta release channel has successfully updated) and no problems/errors/crashes so far

**Comment by jackplug** [comment]
@tanel @IndrekV it's looking like you fixed it in 7.2.206, guys :+1: Everything still seems to be working smoothly and I have not seen any problems
