### ISSUE TITLE
Editing dates in Windows app causes it to crash

### ISSUE THREAD

**Issue by xtoq** [toggl/toggldesktop#1888]
Steps to reproduce
-----

1. Open Toggl desktop.
2. Edit a date of a previous entry.

Expected outcome
-----

- You should be able to edit the date.

Actual outcome
-----

- The date is not edited, the app freezes, and upon restarting the date of the entry you were trying to edit is now in the future. I have 2 November 2016 events in Toggl now.
- It seems like its trying to set a time for the date, because the day always corresponds to the minute of the time the app crashed, although the month is has ranged from August to November.

I submitted feedback via the app, but wanted to put this in the issues in case others are having the same problem.

**Comment by xtoq** [comment]
Dunno if its helpful, but Visual Studio gives the following information: `An unhandled exception of type 'System.StackOverflowException' occurred in WindowsBase.dll` just like #1882.

**Comment by xtoq** [comment]
In addition, now the app won't sync certain of the messed up entries with the web app. I've changed the dates to be correct on the web app, but the desktop app still has the wrong ones. Screenshot is immediately after both a keyboard shortcut sync and choosing sync from the menu.

![toggl](https://cloud.githubusercontent.com/assets/120364/14942041/c4e950a2-0f76-11e6-85bc-06e68b8e2154.png)

**Comment by IndrekV** [comment]
We released new beta version (7.3.316) last week that has fix for the datepicker issues. Please switch to beta channel from the about view and update the app.

**Comment by xtoq** [comment]
I am actually on the beta channel and the version 7.3.316, sorry for not providing that information. I also made a report from the app when it happened. Still having the issues today.

**Comment by IndrekV** [comment]
Thank you for sending info from the app I'll look into the log files for more info.

**Comment by xtoq** [comment]
I sent 2 different logs, about 15 minutes from one another on May 1, ~9:00am.

Here's a step recording with Windows 10 of it happening, as well as a gif of what happens consistently when I attempt to edit a date.

[toggl-step-recording.zip](https://github.com/toggl/toggldesktop/files/245027/toggl-step-recording.zip)

![toggl-date-editing-issues](https://cloud.githubusercontent.com/assets/120364/14954528/aea11df8-1038-11e6-800f-c9bb762d6e00.gif)

**Comment by IndrekV** [comment]
Hi,

I've tried to replicate this many times but am not able. It might be some data issue. Some data is corrupt and is creating this crash. I would like you to back up your local files located in the 'C:\Users\<username>\AppData\Local\TogglDesktop' and called toggldesktop.db 

an then clear app cache.

Here are instructions how to clear app cache https://support.toggl.com/clearing-the-local-data-from-toggl-desktop/

**Comment by IndrekV** [comment]
I was able to reproduce this issue. The latest beta 7.3.318 has fix for this issue.
This was fixed with 1eb01ef2abd3536f2d79bfd9fe5d14c06a549085

**Comment by IndrekV** [comment]
Thank you very much for sharing all the details about this issue.
