### ISSUE TITLE
Input disappears

### ISSUE THREAD

**Issue by thecjharries** [toggl/toggldesktop#2183]
Similar to #1921. I can't reliably duplicate for a recording.

Occasionally I'll enter a description and select a project, then come back later to a completely blank entry.  I was finally able to show a coworker this morning, and thought I should probably report the bug.

```bash
$ rpm --query centos-release
centos-release-7-3.1611.el7.centos.x86_64
$ basename $PWD
toggldesktop_linux_x86_64-7_4_31
```

**Comment by kadrihvl** [comment]
This case sounds similar: 479027 (osx_native_app/7.4.31). Will ask for logs. 
` I should note that I am using keyboard commands to function the app. Once I input the task I'm doing in the first bar, I tab to the project. One I choose the project (again, via keyboard), I select it and tab to the "duration". I key in the duration and hit enter. Nothing happens when I hit enter. The "duration" remains selected, as though it does not want to accept my time. This is a marked change from prior to the OS update. If I "X" out of the popup and do it all again, it takes without an issue. Thus, I have to enter everything twice.`

**Comment by Spica2000** [comment]
I have the same issue with version 7.4.31 (Windows) when selecting from autocomplete task/project either with keyboard or mouse. When I select task/project it disappears after I close tab (sidebar).

**Comment by IndrekV** [comment]
@thecjharries @Spica2000 

We've released a fixed version.  We would very much appreciate if you could test it and see if it fixes the issues with editing entries that you are experiencing.

You can get the fixed version from: 
Windows:
[TogglDesktopInstaller-7.4.45.exe](https://github.com/toggl/toggldesktop/releases/download/v7.4.45/TogglDesktopInstaller-7.4.45.exe)

Linux:
[toggldesktop_linux_x86_64-7_4_45.tar.gz](https://github.com/toggl/toggldesktop/releases/download/v7.4.45/toggldesktop_linux_x86_64-7_4_45.tar.gz)

**Comment by thecjharries** [comment]
@IndrekV I've installed the new version. I don't know that I'll be able to use it enough today to have enough exposure, but I certainly will tomorrow. Thanks!

**Comment by TheSoloJake** [comment]
Case 484173 installed beta and says issue is still occurring, but not at all as often as before.

**Comment by Spica2000** [comment]
Thank you!

I've installed the new version. The issue is seems to be fixed, if it will
happen once again, I will write to you.

**Comment by thecjharries** [comment]
@avandermeyden That's an interesting observation. If I start a task, then quickly open it, type a few characters, and exit, the description will briefly flip to `(no description)`, but then reverts to what I typed. It seems to be a timing thing.

I haven't been able to reproduce so far today on the Linux client.

**Comment by IndrekV** [comment]
We've released a new beta version that addresses the flickering issue. Please get the latest beta (7.4.47) by switching to beta channel from the About view

**Comment by thecjharries** [comment]
Downloading and installing. I'm clocking out in a little bit, but I should be able to test this tomorrow. Thanks!

**Comment by avandermeyden** [comment]
Downloaded it as well.  Looking quite promising in my initial testing.

**Comment by avandermeyden** [comment]
The one flicker I've seen so far is deleting my test task... I deleted it, it went away, it came back for a second but then went away so it worked itself out in the end.  Not perfect, but I can definitely work with that.

**Comment by IndrekV** [comment]
7.4.47 seems to be working ok. Pushed 7.4.47 to stable. I'll create a separate issue for the delete flicker and try to replicate it.

**Comment by thecjharries** [comment]
It looks great on my end. I haven't had any issues today. Thanks again. If something else pops up, I'll open a new issue.

**Comment by Spica2000** [comment]
Dear Toggl,

Unfortunately after last update the Windows app doesn't start at all. I
just hit the icon and nothing happens.
I run Windows 10 x64.

Is it possible to do something?

Best regards,
Vadim

**Comment by skel35** [comment]
Hi Vadim @Spica2000 ,

Please uninstall the app, then download and install the app again from here https://github.com/toggl-open-source/toggldesktop/releases/download/v7.4.1092/TogglDesktopInstaller-x64-7.4.1092.exe or here https://toggl.com/toggl-desktop/ . In case it doesn't help please contact us again mentioning the version number that you have installed.
This week a limited amount of users had accidentally received a broken version, so you were probably among them. Apologies for that, and thanks for contacting us.
