### ISSUE TITLE
User unable to install Toggl Desktop (Win)

### ISSUE THREAD

**Issue by zdericnina** [toggl/toggldesktop#2192]
> When I try to install the desktop app for windows, the installer never completes.

He tried removing the cache but couldn't find the TogglDesktop folder, he also tried installing the latest version.

![2017-06-08_10-35-42](https://user-images.githubusercontent.com/19727123/26977286-997fde64-4d27-11e7-8975-0d1ae86d6d7e.png)

Case/482177

**Comment by IndrekV** [comment]
Fix will be available with next release.

**Comment by IndrekV** [comment]
This is fixed in latest beta (7.4.47)

**Comment by zdericnina** [comment]
One User reported to still have issues with the installation even with 7.4.7.

![capture](https://user-images.githubusercontent.com/19727123/27171584-4ee1f2a4-51b2-11e7-94af-0f06ccf231cb.jpg)


Case/480298

**Comment by IndrekV** [comment]
I think you meant version 7.4.47 instead of 7.4.7.

The error is different. The one in the beginning of the issue was about some old installer removing thing. The last screenshot is shown if toggl desktop is still running when user is trying to install new version. With version 7.4.47 the installer actually shows a notification right before this error message that warns users that Toggl Desktop is still running and should be closed.

<img width="502" alt="screen shot 2017-06-12 at 16 17 05" src="https://user-images.githubusercontent.com/842229/27035603-a1d90c38-4f8a-11e7-8c1f-b1d290243508.png">

User should just close Toggl Desktop from task manager (Ctrl+Alt+Del to open task manager in windows)

**Comment by IndrekV** [comment]
From version 7.4.52 the installer force closes all instances of Toggl Desktop before starting install process. The `Error opening file for writing ...` should not be happening anymore.
