### ISSUE TITLE
Syncing glitches

### ISSUE THREAD

**Issue by fonorobert** [toggl/toggldesktop#2196]
Several users reported various syncing glitches when starting new timers: selected project is not retained, entered description is cleared out, having to close and reopen the editing popup to be able to enter description or select project.

Below is reproduction of some of these issues from v7.4.38 of the Mac app but users are reporting similar issues on 7.4.45 as well as the stable and latest beta versions of the Windows app:

![desktop](https://user-images.githubusercontent.com/6963710/27079664-d1a61cfe-5038-11e7-9efa-9cbed5e99e4c.gif)

From the above it seems the issues might be happening because of the app syncing down eg. the empty description while it's being edited locally.
This seems to be a fairly broad issue and probably needs more investigation. It might be tied to https://github.com/toggl/toggldesktop/issues/2195 as well as https://github.com/toggl/toggldesktop/issues/2185

**Comment by TheSoloJake** [comment]
Also case/487031, incl. desktop log files

**Comment by IndrekV** [comment]
It's all connected to updated sync logic. We've released a new beta version (7.4.47) that addresses the the syncing and updating local data and avoids flickering between different data.

**Comment by IndrekV** [comment]
7.4.47 seems to be working ok. Pushed 7.4.47 to stable.

**Comment by ericjeker** [comment]
Hi guys,

I have reported many of those sync glitches to the support before. Yesterday the support sent me v7.4.47. I still have those glitches today.

I am on Win10 Pro.

For me this is not solved. Entering time is pretty erratic and uncomfortable with loss of entered data.

**Comment by IndrekV** [comment]
@ericjeker Thanks for letting us know. We went deeper to find what can cause this. We have reworked the whole syncing part to match the way it used to work before the glitches. We've released a beta version with fixes v7.4.49. Switch to beta channel if you want to check out the fixes now or wait until next week when it will be pushed to stable.

**Comment by ericjeker** [comment]
Hi @IndrekV , so I am testing the beta version since your message and it seems to be working much better. I have not encountered any glitch anymore.

**Comment by AdamGerthel** [comment]
Would be nice if you (someone?) release a new version on the Mac App Store. Current version there is 7.4.11 which is still suffering from these issues.

**Comment by IndrekV** [comment]
@AdamGerthel New version released to AppStore.

**Comment by IndrekV** [comment]
@AdamGerthel New version released to AppStore (version 7.4.58).

**Comment by AdamGerthel** [comment]
@IndrekV I've already switched to the version that's available here, but thanks for letting me know!
