### ISSUE TITLE
Toggl stopped working abnormally

### ISSUE THREAD

**Issue by Spurlos** [toggl/toggldesktop#2272]
Today Toggle showed me a popup messaged saying "Data that you are sending is not valid/acceptable". I have tried restarting the app, syncing, clearing the cache. After clearing the caches I can't log in using Google Auth, i'm just receiving this popup again. Reinstalled the latest stable version v7.4.58, no luck. Web-app works normally as before, i can log there. Any suggestions?

![image](https://user-images.githubusercontent.com/667533/30960810-d66ce4f8-a44c-11e7-83ca-4a8a69472cb6.png)

**Comment by tobihagemann** [comment]
Having the same issue on macOS with a "regular" (non-Google) account. I also uninstalled everything / cleared the cache. Now I'm stuck. :sob:

**Comment by sgr12** [comment]
Getting the same error on macOS on 7.4.58 with Google auth. I'm seeing this error for the first time. Could be a temporary server-related issue.

<img width="332" alt="screenshot at sep 28 15-39-42" src="https://user-images.githubusercontent.com/11720544/30961310-5acce85e-a463-11e7-93b0-65167632e6ad.png">

**Comment by madorin** [comment]
Having the same issue, from about one hour. Any issues on your back-end service?

**Comment by hmijail** [comment]
Same here, in macOS 10.12 Sierra / Toggl 7.4.58 (but I'm in the beta channel, in case that matters). 

Even if this is just about some temporary server problem, it seems evident that Toggl needs some error message revamping. What is wrong exactly? What should the user do? etc

**Comment by hmijail** [comment]
FWIW I wrote in their feedback form and got a quick reply: "We're aware of the issue and our developers are currently working on it, we're very sorry for the inconvenience."

**Comment by PeterBowater** [comment]
Also an issue here, thank you!

It is failing to sync my different projects locally, though I can sort of record time with the app, it's not right for sure!

**Comment by tobihagemann** [comment]
Seems to be fixed!

**Comment by PeterBowater** [comment]
Hmm, I still have a load of my projects missing, and it is removing them from tasks in my work log!

**Comment by PeterBowater** [comment]
I cleared by toggle desktop cache and the projects have reappeared, and started working normally, at least so far!

**Comment by IndrekV** [comment]
Thank you for such active response to this issue. We will look more into this, but currently it looks like it was a server configuration issue that should be solved.

**Comment by IndrekV** [comment]
closed with #2273

**Comment by Frolipon** [comment]
Hello,

Unfortunately, I still have this issue :-/

Can't connect from desktop app from imac OSX 10.11.6
"Data that you are sending is not valid/acceptable" on the login interface.

**Comment by IndrekV** [comment]
@Frolipon I've pushed out a new beta version with the fix. Please switch to beta channel from the About view or download the new beta from [v7.4.68](https://toggl.com/api/v8/installer?app=td&platform=darwin&channel=beta)

**Comment by Frolipon** [comment]
Hello,

Thanks for that. The link to the beta don't seem to work, but I donwloaded the latest available version (7.4.58) and now it seems to work just fine.

Have a nice day!
