### ISSUE TITLE
Mac App keeps crashing and/or won't open

### ISSUE THREAD

**Issue by intes** [toggl/toggldesktop#2315]
DiagnosticReport
[TogglDesktop_2017-11-03-202208.crash.txt](https://github.com/toggl/toggldesktop/files/1441940/TogglDesktop_2017-11-03-202208.crash.txt)
Reinstall not help.

**Comment by TheSoloJake** [comment]
Related to #2314

**Comment by intes** [comment]
Reinstall not help.

**Comment by thewozjesse** [comment]
Having the same issue. Reinstall of newest update didn't help.
[toggl_crash_report_2017-11-03.txt](https://github.com/toggl/toggldesktop/files/1442005/toggl_crash_report_2017-11-03.txt)

**Comment by IndrekV** [comment]
Seems most of the issues are with MacOs 10.9.* and 10.10.*
I'm able to replicate the issue and will look for a fix. I've reverted the latest stable version to previous version until this is solved.

**Comment by song4Him** [comment]
Just commenting to say that I've had the same problem with my Mac OS X 10.10.5. First problem yesterday afternoon, when I closed out Toggl for some reason and it refused to reopen (repeatedly tried opening from Launchpad and Applications, and nothing happened). I completely uninstalled it, and even removed my .plist file from ~/Library/Preferences/ . Have reinstalled several times and done several restarts, but nothing is working.

Where do I find an older version of the app? Using the webapp for now, but it feels clunky compared to what I'm used to!

**Comment by siramsay** [comment]
having the same problem.

I can delete the app from application and re-install everyday but if I try to open after shutting down my Mac (10.9.5) it won't open... re-install from dmg and all is fine... Groundhog day...

V. TogglDesktop-7_4_58.dmg

**Comment by IndrekV** [comment]
I've fixed the updater issue. I should not download the broken release anymore. Thank you for your feedback.

**Comment by IndrekV** [comment]
I've built a fixed version. I tested it with MacOs 10.10 machine that also failed with the broken version. It seems to work ok. Could someone @intes @thewozjesse @song4Him @siramsay please be so kind to verify this version also works ok for them [download MacOs version 7.4.84](https://github.com/toggl/toggldesktop/releases/download/v7.4.84/TogglDesktop-7_4_84.dmg)

**Comment by J-Baese** [comment]
Still having this issue with MacOS version 10.13.2 - was working great for a few days and then just decided to kick me out stating invalid user/password. Log back in (with correct details) get into app for 2secs and it kicks me out again. Reinstalled, restarted etc. still same issue. I've attached the crash report.
[toggl-crashreport.txt](https://github.com/toggl/toggldesktop/files/1628900/toggl-crashreport.txt)

**Comment by IndrekV** [comment]
@J-Baese This problem seems to be different than the one described in this issue. Please try to send feedback from the app so we get the app log files and can look more into it. Mention in the feedback that it's For Indrek.

**Comment by IndrekV** [comment]
Created separate issue for the crash issue that appeared after login. #2360
