### ISSUE TITLE
macOS app crashing

### ISSUE THREAD

**Issue by ricotheque** [toggl/toggldesktop#2411]
/case/658914

osx_native_app/7.4.129

"Hello, Toggl continues to crash especially on the initial time I open it. I submitted before and cleared Kopsik folder as suggested. "

New log is available in case link.

**Comment by IndrekV** [comment]
This issue was probably caused by some data handling issues. It should be fixed in the latest beta 7.4.155

**Comment by ricotheque** [comment]
Thanks! 👍

**Comment by ricotheque** [comment]
@IndrekV Unfortunately he's still encountering some problems 

/case/712387

**Comment by IndrekV** [comment]
The new crash issue is different as it crashes when quitting the app. I created a new issue for it #2467
