### ISSUE TITLE
Autocomplete do not offer tasks for the project

### ISSUE THREAD

**Issue by lukassivak** [toggl/toggldesktop#2542]
If we try to find a project by the name, project tasks are not offered and can't be selected. For some projects it works, for plenty of others it doesn't.

**Comment by IndrekV** [comment]
This should be fixed in the latest beta on mac (7.4.235) and latest stable for windows (7.4.237)

To switch channel just change the channel selection in the About view and app will trigger the update.

**Comment by lukassivak** [comment]
Thanks. I have macOS beta version (7.4.236) and the bug is still present.

**Comment by lukassivak** [comment]
It works, thanks

**Comment by jaydrogers** [comment]
Worked for me too, thanks!
